import type { Metadata } from "next";
import { Mona_Sans, Quicksand } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";


const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${monaSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
